export type UniSliderChangeEventDetail = {
  value : number
}

// #ifdef WEB
class UniCustomEvent<T> {
  detail : T
  constructor(type : string, detail : T) {
    // this.type = type
    this.detail = detail
  }
}
// #endif

export class _UniSliderChangeEvent extends UniCustomEvent<UniSliderChangeEventDetail> {
  constructor(value : number) {
    super('change', { value } as UniSliderChangeEventDetail)
  }
}